name: SSH Deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      label:
        description: "Label"
        type: string
        required: true

jobs:
  ssh_deploy:
    name: Bundle release and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Check out codebase
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: volta-cli/action@v4
      - name: Install dependencies
        run: npm ci
      - name: Bundle release
        run: npm run build
      - name: Deploy release
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          ARGS: "-az --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "release/"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET: ${{ secrets.TARGET }}
